src/accounts/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView


app_name = 'accounts'
urlpatterns = [
    path(
        'register/',
        RegisterView.as_view(),
        name='accounts-register'
    ),
    path(
        'login/',
        LoginView.as_view(),
        name='accounts-login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='accounts-logout'
    ),
]

src/dev_social_network/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path(
        'dev/',
        include('pages.urls', namespace='pages')
    ),
    path(
        'dev/accounts/',
        include('accounts.urls', namespace='accounts')
    ),
    path(
        'dev/posts/',
        include('posts.urls', namespace='posts')
    ),
    path(
        'dev/posts/',
        include('likes.urls', namespace='likes')
    ),
    path(
        'dev/posts/',
        include('unlikes.urls', namespace='unlikes')
    ),
    path(
        'dev/posts/',
        include('comments.urls', namespace='comments')
    ),
    path(
        'dev/profiles/',
        include('profiles.urls', namespace='profiles')
    ),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/likes/urls.py
from django.urls import path
from .views import PostLikeView

app_name = 'likes'
urlpatterns = [
    path(
      '<int:id>/like/',
      PostLikeView.as_view(),
      name='post-likes'
    )
]

src/pages/urls.py
from django.urls import path
from .views import IndexView, DashboardView, AboutView

app_name = 'pages'
urlpatterns = [
    path(
        'home/',
        IndexView.as_view(),
        name='home-view'
    ),
    path(
        'dashboard/',
        DashboardView.as_view(),
        name='dashboard-view'
    ),
    path(
        'about/',
        AboutView.as_view(),
        name='about-view'
    )
]

src/posts/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView
)


app_name = 'posts'
urlpatterns = [
    path(
        '',
        PostListView.as_view(),
        name='posts-list'
    ),
    path(
        '<int:id>/detail/',
        PostDetailView.as_view(),
        name='posts-detail'
    ),
    path(
        '<int:id>/update/',
        PostUpdateView.as_view(),
        name='posts-update'
    ),
    path(
        '<int:id>/delete/',
        PostDeleteView.as_view(),
        name='posts-delete'
    )
]

src/profiles/urls.py
from django.urls import path
from .views import (
    ProfileListView,
    ProfileCreateView,
    ProfileDetailView,
    ProfileUpdateView,
    ProfileDeleteView,
    EducationListView,
    EducationCreateView,
    EducationDetailView,
    EducationUpdateView,
    EducationDeleteView,
    ExperienceListView,
    ExperienceCreateView,
    ExperienceDetailView,
    ExperienceUpdateView,
    ExperienceDeleteView,
    SocialCreateView,
    SocialDetailView,
    SocialUpdateView,
    SocialDeleteView
)

app_name = 'profiles'
urlpatterns = [
    path(
        '',
        ProfileListView.as_view(),
        name='profiles-list'
    ),
    path(
        'create/',
        ProfileCreateView.as_view(),
        name='profiles-create'
    ),
    path(
        '<int:id>/detail/',
        ProfileDetailView.as_view(),
        name='profiles-detail'
    ),
    path(
        '<int:id>/delete/',
        ProfileDeleteView.as_view(),
        name='profiles-delete'
    ),
    path(
        '<int:id>/update/',
        ProfileUpdateView.as_view(),
        name='profiles-update'
    ),
    path(
        '<int:id>/educations/',
        EducationListView.as_view(),
        name='educations-list'
    ),
    path(
        '<int:id>/experiences/',
        ExperienceListView.as_view(),
        name='experiences-list'
    ),
    path(
        '<int:id>/educations/create',
        EducationCreateView.as_view(),
        name='educations-create'
    ),
    path(
        '<int:id>/experiences/create',
        ExperienceCreateView.as_view(),
        name='experiences-create'
    ),
    path(
        '<int:id>/socials',
        SocialDetailView.as_view(),
        name='socials-detail'
    ),
    path(
        '<int:id>/socials/create',
        SocialCreateView.as_view(),
        name='socials-create'
    ),
    path(
        '<int:id>/socials/update',
        SocialUpdateView.as_view(),
        name='socials-update'
    ),
    path(
        '<int:id>/socials/delete',
        SocialDeleteView.as_view(),
        name='socials-delete'
    ),
    path(
        '<int:profile_id>/educations/<int:education_id>/detail',
        EducationDetailView.as_view(),
        name='educations-detail'
    ),
    path(
        '<int:profile_id>/experiences/<int:experience_id>/detail',
        ExperienceDetailView.as_view(),
        name='experiences-detail'
    ),
    path(
        '<int:profile_id>/educations/<int:education_id>/update',
        EducationUpdateView.as_view(),
        name='educations-update'
    ),
    path(
        '<int:profile_id>/experiences/<int:experience_id>/update',
        ExperienceUpdateView.as_view(),
        name='experiences-update'
    ),
    path(
        '<int:profile_id>/educations/<int:education_id>/delete',
        EducationDeleteView.as_view(),
        name='educations-delete'
    ),
    path(
        '<int:profile_id>/experiences/<int:experience_id>/delete',
        ExperienceDeleteView.as_view(),
        name='experiences-delete'
    ),
]

src/templates/layouts/alert.html
<div class="container mt-3">
  {% for message in messages %}
  {% if message.tags == 'error' %}
  <div class="alert alert-danger">{{message}}</div>
  {% endif %}
  {% if message.tags == 'success' %}
  <div class="alert alert-success">{{message}}</div>
  {% endif %}
  {% endfor %}
</div>

src/templates/layouts/footer.html
<hr>
<footer class="footer">
  <div class="container">
    <p class="lead text-muted text-center">
      <strong>Dev Network</strong> &copy; & All rights reserved to <strong>ankurshr01</strong>
    </p>
  </div>
</footer>

src/templates/layouts/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">Dev Network</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
      aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:dashboard-view' %}">Dashboard</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:home-view' %}">Home</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profiles:profiles-list' %}">Profiles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:posts-list' %}">Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:about-view' %}">About</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:accounts-logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:accounts-register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:accounts-login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>


<!-- <li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true"
    aria-expanded="false">Dropdown</a>
  <div class="dropdown-menu" aria-labelledby="dropdownId">
    <a class="dropdown-item" href="#">Action 1</a>
    <a class="dropdown-item" href="#">Action 2</a>
  </div>
</li> -->