src/dev_social_network/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path(
        'dev/',
        include('pages.urls', namespace='pages')
    ),
    path(
        'dev/accounts/',
        include('accounts.urls', namespace='accounts')
    ),
    path(
        'dev/posts/',
        include('posts.urls', namespace='posts')
    ),
    path(
        'dev/posts/',
        include('likes.urls', namespace='likes')
    ),
    path(
        'dev/posts/',
        include('unlikes.urls', namespace='unlikes')
    ),
    path(
        'dev/posts/',
        include('comments.urls', namespace='comments')
    ),
    path(
        'dev/profiles/',
        include('profiles.urls', namespace='profiles')
    ),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/likes/urls.py
from django.urls import path
from .views import PostLikeView

app_name = 'likes'
urlpatterns = [
    path(
      '<int:id>/like/',
      PostLikeView.as_view(),
      name='post-likes'
    )
]

src/posts/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView
)


app_name = 'posts'
urlpatterns = [
    path(
        '',
        PostListView.as_view(),
        name='posts-list'
    ),
    path(
        '<int:id>/detail/',
        PostDetailView.as_view(),
        name='posts-detail'
    ),
    path(
        '<int:id>/update/',
        PostUpdateView.as_view(),
        name='posts-update'
    ),
    path(
        '<int:id>/delete/',
        PostDeleteView.as_view(),
        name='posts-delete'
    )
]

src/comments/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.urls import reverse

from posts.models import Post

User = get_user_model()


# COMMENT MANAGER
class CommentManager(models.Manager):
  def get_comment(self, p_id, c_id, user):
    return get_object_or_404(self, post=p_id, pk=c_id, owner=user)


# COMMENT MODEL
class Comment(models.Model):
  text = models.TextField(default="awesome!")
  post = models.ForeignKey(
    Post,
    default=1,
    on_delete=models.CASCADE
  )
  owner = models.ForeignKey(
    User,
    default=1,
    on_delete=models.CASCADE
  )

  objects = CommentManager()

  def __str__(self, *args, **kwargs):
    return self.text

  def get_delete_url(self, *args, **kwargs):
    return reverse(
      'comments:comments-delete',
      kwargs={'post_id': self.post.pk, 'comment_id': self.pk}
    )

  def get_update_url(self, *args, **kwargs):
    return reverse(
      'comments:comments-update',
      kwargs={'post_id': self.post.pk, 'comment_id': self.pk}
    )
  

src/likes/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.urls import reverse

from posts.models import Post

User = get_user_model()


# Like Manager
class LikeManager(models.Manager):
  def find_is_liked(self, post, user):
    return self.filter(post=post, owner=user)

  def create_like(self, post, user):
    like = self.create(post=post, owner=user)
    like.save()


# LIKE MODEL
class Like(models.Model):
  post = models.ForeignKey(
    Post,
    default=1,
    on_delete=models.CASCADE
  )
  owner = models.ForeignKey(
    User,
    default=1,
    on_delete=models.CASCADE
  )

  objects = LikeManager()

  def __str__(self, *args, **kwargs):
    return self.post.title

src/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.urls import reverse

User = get_user_model()

# POST MANAGER
class PostManager(models.Manager):
  def get_posts(self, *args, **kwargs):
    return self.all()

  def get_post(self, post_id, *args, **kwargs):
    return get_object_or_404(self, id=post_id)

  def get_user_posts(self, owner, *args, **kwargs):
    return self.filter(owner=owner)

  def get_user_post(self, post_id, user, *args, **kwargs):
    return get_object_or_404(self, pk=post_id, owner=user)


# POST MODEL
class Post(models.Model):
  title = models.CharField(max_length=100)
  description = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  owner = models.ForeignKey(
    User,
    default=1,
    on_delete=models.CASCADE,
    null=True
  )

  objects = PostManager()

  def __str__(self, *args, **kwargs):
    return self.title

  def get_absolute_url(self, *args, **kwargs):
    return reverse('posts:posts-detail', kwargs={'id': self.pk})
  
  def get_delete_url(self, *args, **kwargs):
    return reverse('posts:posts-delete', kwargs={'id': self.pk})

  def get_update_url(self, *args, **kwargs):
    return reverse('posts:posts-update', kwargs={'id': self.pk})

  def get_like_url(self, *args, **kwargs):
    return reverse('likes:post-likes', kwargs={'id': self.pk})
  
  def get_unlike_url(self, *args, **kwargs):
    return reverse('unlikes:post-unlikes', kwargs={'id': self.pk})

  def get_comment_create_url(self, *args, **kwargs):
    return reverse('comments:comments-create', kwargs={'id': self.pk})

src/unlikes/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.urls import reverse

from posts.models import Post

User = get_user_model()


# UNLIKE MANAGER
class UnlikeManager(models.Manager):
  def find_is_unliked(self, post, user):
    return self.filter(post=post, owner=user)
  
  def create_unlike(self, post, user):
    unlike = self.create(post=post, owner=user)
    unlike.save()


# UNLIKE MODEL
class Unlike(models.Model):
  post = models.ForeignKey(
    Post,
    default=1,
    on_delete=models.CASCADE
  )
  owner = models.ForeignKey(
    User,
    default=1,
    on_delete=models.CASCADE
  )

  objects = UnlikeManager()

  def __str__(self, *args, **kwargs):
    return self.post.title

src/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
  title = forms.CharField(
    widget=forms.TextInput(
      attrs={
        'class': 'form-control form-control-lg',
        'placeholder': 'Enter Title'
      }
    )
  )

  description = forms.CharField(
    widget=forms.Textarea(
      attrs={
        'class': 'form-control form-control-lg',
        'placeholder': 'Enter Description',
        'rows': 3
      }
    )
  )

  class Meta:
    model = Post
    fields = ('title', 'description',)

  def clean_title(self, *args, **kwargs):
    title = self.cleaned_data.get('title')
    if not title.strip():
      raise forms.ValidationError('Invalid title!')
    else:
      return title

  def clean_description(self, *args, **kwargs):
    description = self.cleaned_data.get('description')
    if not description.strip():
      raise forms.ValidationError('Invalid description!')
    else:
      return description

src/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, DetailView, UpdateView, DeleteView

from .models import Post
from .forms import PostForm


# POST LIST VIEW
class PostListView(View):
  model = Post
  form = PostForm
  template_name = 'posts/post_list.html'
  context = {}

  def get(self, request, *args, **kwargs):
    qs = self.model.objects.get_posts()
    form = self.form()
    self.context['title'] = 'Posts'
    self.context['posts'] = qs
    self.context['form'] = form
    return render(request, self.template_name, self.context)

  def post(self, request, *args, **kwargs):
    form = self.form(request.POST)
    if form.is_valid():
      instance = form.save(commit=False)
      instance.owner = self.request.user
      instance.save()
      messages.success(request, 'Post has been added to feed!')
      return redirect('posts:posts-list')
    messages.error(request, 'Oop! Enter valid details!')
    return reverse('posts:posts-list')


# POST DETAIL VIEW
class PostDetailView(DetailView):
  queryset = Post.objects.all()
  context_object_name = 'post'
  lookup = 'id'
  
  def get_object(self, *args, **kwargs):
    return get_object_or_404(Post, pk=self.kwargs.get(self.lookup))
  
  def get_context_data(self, *args, **kwargs):
    context = super(PostDetailView, self).get_context_data(*args, **kwargs)
    context['title'] = 'Post Detail'
    return context


# POST UPDATE VIEW
class PostUpdateView(LoginRequiredMixin, UpdateView):
  queryset = Post.objects.all()
  form_class = PostForm
  context_object_name = 'post'
  template_name = 'posts/post_update.html'
  lookup = 'id'

  def get_object(self, *args, **kwargs):
    return Post.objects.get_user_post(
      self.kwargs.get(self.lookup),
      self.request.user
    )

  def get_context_data(self, *args, **kwargs):
    context = super(PostUpdateView, self).get_context_data(*args, **kwargs)
    context['title'] = 'Post Update'
    return context
  
  def get_success_url(self, *args, **kwargs):
    messages.success(self.request, 'Post has been updated successfully!')
    return reverse('posts:posts-detail', kwargs={'id': self.kwargs.get(self.lookup)})


# POST DELETE VIEW
class PostDeleteView(LoginRequiredMixin, DeleteView):
  queryset = Post.objects.all()
  context_object_name = 'post'
  template_name = 'posts/post_delete.html'
  lookup = 'id'

  def get_object(self, *args, **kwargs):
    return Post.objects.get_user_post(
      self.kwargs.get(self.lookup),
      self.request.user
    )
  
  def get_context_data(self, *args, **kwargs):
    context = super(PostDeleteView, self).get_context_data(*args, **kwargs)
    context['title'] = 'Post Delete'
    return context

  def get_success_url(self, *args, **kwargs):
    messages.success(self.request, 'Post has been deleted!')
    return reverse('posts:posts-list')

src/posts/templates/posts/post_create.html
{% extends 'base.html' %}

{% block content %}
<div class="post-list">
  <h3 class="page-heading">Cre</h3>

</div>
{% endblock content %}

src/posts/templates/posts/post_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="post-delete">
  <h3 class="page-heading">Delete Post</h3>
  <div class="card">
    <div class="card-header">
      <h5>Are you sure? You wanna delete this post?</h5>
    </div>
    <div class="card-body">
      <h4 class="card-title">{{post.title}}</h4>
      <p class="card-text">{{post.description}}</p>
      <form action="" method="POST"> {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes</button>
        <a href="{{post.get_absolute_url}}" type="button" class="btn btn-dark">No</a>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

src/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="post-detail">
  <h3 class="page-heading">Post Detail</h3>
  <div class="card">
    <div class="card-header text-center">
      <h4 class="card-title m-0">{{post.title}}</h4>
    </div>
    <div class="card-body text-center">
      <div class="card-left">
        <p class="card-text">Description: {{post.description}}</p>
        <p class="card-text">Author: {{post.owner}}</p>
        <p class="card-text">Created At: {{post.created_at}}</p>
      </div>
      <br>
      <form action="" class="">
        {% if user.is_authenticated %}
        <a href="{{post.get_comment_create_url}}" type="button" class="btn btn-dark">Comment</a>
        {% endif %}
        {% if user.is_authenticated and post.owner == user %}
        <a href="{{post.get_update_url}}" type="button" class="btn btn-info">Edit</a>
        <a href="{{post.get_delete_url}}" type="submit" class="btn btn-danger">Delete</a>
        {% endif %}
      </form>
    </div>
    {% if post.comment_set.all %}
    <div class="card-footer">
      <div class="container">
        <h5 class="m-0">Comments</h5>
        <hr>
        {% for comment in post.comment_set.all %}
        <div class="mb-2 d-flex">
          <div>
            <span class="">{{comment.text}}</span><br>
            <small>{{comment.owner}}</small>
          </div>
          {% if comment.owner == user %}
          <form action="" class="">
            <a href="{{comment.get_update_url}}" class="btn btn-sm btn-outline-dark">Edit</a>
            <a href="{{comment.get_delete_url}}" class="btn btn-sm btn-danger">Delete</a>
          </form>
          {% endif %}
        </div>
        <hr>
        {% endfor %}
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock content %}

src/posts/templates/posts/post_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="post-list">
  <header class="page-header d-flex">
    <h3 class="page-heading">Posts Feed</h3>
    {% if user.is_authenticated %}
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modelId">
      New Post!
    </button>
    {% endif %}
  </header>
  <hr>
  {% if not posts.exists %}
  <p class="lead text-muted">No posts added yet..</p>
  {% else %}
  {% for post in posts %}
  <div class="card card-posts my-2">
    <div class="card-body d-flex">
      <div class="card-left">
        <p class="lead m-0">{{post.title}}</p>
        <small class="text-muted">Author: {{post.owner}}</small>
      </div>
      <div class="card-right">
        <a href="{{post.get_like_url}}" class="btn btn-sm">Like {{post.like_set.all|length}}</a>
        <a href="{{post.get_unlike_url}}" class="btn btn-sm">Unlike {{post.unlike_set.all|length}}</a>
        <a href="{{post.get_absolute_url}}" class="btn btn-outline-primary ml-3">Explore
          {{post.comment_set.all|length}}</a>
      </div>
    </div>
  </div>
  {% endfor %}
  {% endif %}


  <!-- Modal -->
  <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Create Post</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST"> {% csrf_token %}
          <div class="modal-body">
            {{ form|crispy }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-success">Create</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

src/posts/templates/posts/post_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="post-update">
  <h3 class="page-heading">Update Post</h3>
  <hr>
  <form action="" method="POST"> {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-lg btn-success">Update</button>
    <a href="{{post.get_absolute_url}}" class="btn btn-lg btn-dark">Discard</a>
  </form>
</div>
{% endblock content %}